Search.appendIndex(
    [
                {
            "fqsen": "\\SamIT\\abac\\AuthManager",
            "name": "AuthManager",
            "summary": "",
            "url": "classes/SamIT-abac-AuthManager.html"
        },                {
            "fqsen": "\\SamIT\\abac\\AuthManager\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-abac-AuthManager.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\AuthManager\u003A\u003AstorePartial\u0028\u0029",
            "name": "storePartial",
            "summary": "",
            "url": "classes/SamIT-abac-AuthManager.html#method_storePartial"
        },                {
            "fqsen": "\\SamIT\\abac\\AuthManager\u003A\u003AgetPartial\u0028\u0029",
            "name": "getPartial",
            "summary": "Checks\u0020the\u0020partial\u0020result\u0020cache",
            "url": "classes/SamIT-abac-AuthManager.html#method_getPartial"
        },                {
            "fqsen": "\\SamIT\\abac\\AuthManager\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "",
            "url": "classes/SamIT-abac-AuthManager.html#method_check"
        },                {
            "fqsen": "\\SamIT\\abac\\AuthManager\u003A\u003Agrant\u0028\u0029",
            "name": "grant",
            "summary": "",
            "url": "classes/SamIT-abac-AuthManager.html#method_grant"
        },                {
            "fqsen": "\\SamIT\\abac\\AuthManager\u003A\u003Arevoke\u0028\u0029",
            "name": "revoke",
            "summary": "",
            "url": "classes/SamIT-abac-AuthManager.html#method_revoke"
        },                {
            "fqsen": "\\SamIT\\abac\\AuthManager\u003A\u003AgetRepository\u0028\u0029",
            "name": "getRepository",
            "summary": "",
            "url": "classes/SamIT-abac-AuthManager.html#method_getRepository"
        },                {
            "fqsen": "\\SamIT\\abac\\AuthManager\u003A\u003AresolveSubject\u0028\u0029",
            "name": "resolveSubject",
            "summary": "",
            "url": "classes/SamIT-abac-AuthManager.html#method_resolveSubject"
        },                {
            "fqsen": "\\SamIT\\abac\\AuthManager\u003A\u003AMAX_DEPTH",
            "name": "MAX_DEPTH",
            "summary": "",
            "url": "classes/SamIT-abac-AuthManager.html#constant_MAX_DEPTH"
        },                {
            "fqsen": "\\SamIT\\abac\\AuthManager\u003A\u003A\u0024depth",
            "name": "depth",
            "summary": "",
            "url": "classes/SamIT-abac-AuthManager.html#property_depth"
        },                {
            "fqsen": "\\SamIT\\abac\\AuthManager\u003A\u003A\u0024partialResults",
            "name": "partialResults",
            "summary": "",
            "url": "classes/SamIT-abac-AuthManager.html#property_partialResults"
        },                {
            "fqsen": "\\SamIT\\abac\\AuthManager\u003A\u003A\u0024ruleEngine",
            "name": "ruleEngine",
            "summary": "",
            "url": "classes/SamIT-abac-AuthManager.html#property_ruleEngine"
        },                {
            "fqsen": "\\SamIT\\abac\\AuthManager\u003A\u003A\u0024permissionRepository",
            "name": "permissionRepository",
            "summary": "",
            "url": "classes/SamIT-abac-AuthManager.html#property_permissionRepository"
        },                {
            "fqsen": "\\SamIT\\abac\\AuthManager\u003A\u003A\u0024resolver",
            "name": "resolver",
            "summary": "",
            "url": "classes/SamIT-abac-AuthManager.html#property_resolver"
        },                {
            "fqsen": "\\SamIT\\abac\\AuthManager\u003A\u003A\u0024environment",
            "name": "environment",
            "summary": "",
            "url": "classes/SamIT-abac-AuthManager.html#property_environment"
        },                {
            "fqsen": "\\SamIT\\abac\\engines\\SimpleEngine",
            "name": "SimpleEngine",
            "summary": "",
            "url": "classes/SamIT-abac-engines-SimpleEngine.html"
        },                {
            "fqsen": "\\SamIT\\abac\\engines\\SimpleEngine\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-abac-engines-SimpleEngine.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\engines\\SimpleEngine\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "",
            "url": "classes/SamIT-abac-engines-SimpleEngine.html#method_check"
        },                {
            "fqsen": "\\SamIT\\abac\\engines\\SimpleEngine\u003A\u003A\u0024rules",
            "name": "rules",
            "summary": "",
            "url": "classes/SamIT-abac-engines-SimpleEngine.html#property_rules"
        },                {
            "fqsen": "\\SamIT\\abac\\exceptions\\NestingException",
            "name": "NestingException",
            "summary": "Class\u0020NestingException",
            "url": "classes/SamIT-abac-exceptions-NestingException.html"
        },                {
            "fqsen": "\\SamIT\\abac\\exceptions\\NestingException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-abac-exceptions-NestingException.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\exceptions\\UnresolvableException",
            "name": "UnresolvableException",
            "summary": "",
            "url": "classes/SamIT-abac-exceptions-UnresolvableException.html"
        },                {
            "fqsen": "\\SamIT\\abac\\exceptions\\UnresolvableException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020is\u0020final\u0020so\u0020that\u0020we\u0020can\u0020safely\u0020use\u0020the\u0020static\u0020\u0060forSubject\u0060\u0020constructor\u0020for\u0020subclasses",
            "url": "classes/SamIT-abac-exceptions-UnresolvableException.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\exceptions\\UnresolvableException\u003A\u003AforSubject\u0028\u0029",
            "name": "forSubject",
            "summary": "",
            "url": "classes/SamIT-abac-exceptions-UnresolvableException.html#method_forSubject"
        },                {
            "fqsen": "\\SamIT\\abac\\exceptions\\UnresolvableSourceException",
            "name": "UnresolvableSourceException",
            "summary": "",
            "url": "classes/SamIT-abac-exceptions-UnresolvableSourceException.html"
        },                {
            "fqsen": "\\SamIT\\abac\\exceptions\\UnresolvableTargetException",
            "name": "UnresolvableTargetException",
            "summary": "",
            "url": "classes/SamIT-abac-exceptions-UnresolvableTargetException.html"
        },                {
            "fqsen": "\\SamIT\\abac\\helpers\\AuthorizableSerializer",
            "name": "AuthorizableSerializer",
            "summary": "",
            "url": "classes/SamIT-abac-helpers-AuthorizableSerializer.html"
        },                {
            "fqsen": "\\SamIT\\abac\\helpers\\AuthorizableSerializer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-abac-helpers-AuthorizableSerializer.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\helpers\\AuthorizableSerializer\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/SamIT-abac-helpers-AuthorizableSerializer.html#method___invoke"
        },                {
            "fqsen": "\\SamIT\\abac\\helpers\\AuthorizableSerializer\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/SamIT-abac-helpers-AuthorizableSerializer.html#method_serialize"
        },                {
            "fqsen": "\\SamIT\\abac\\helpers\\AuthorizableSerializer\u003A\u003A\u0024separator",
            "name": "separator",
            "summary": "",
            "url": "classes/SamIT-abac-helpers-AuthorizableSerializer.html#property_separator"
        },                {
            "fqsen": "\\SamIT\\abac\\helpers\\Cache",
            "name": "Cache",
            "summary": "Helper\u0020class\u0020for\u0020repositories\u0020that\u0020want\u0020to\u0020do\u0020some\u0020kind\u0020of\u0020caching\u0020on\u0020grant\u0020checks",
            "url": "classes/SamIT-abac-helpers-Cache.html"
        },                {
            "fqsen": "\\SamIT\\abac\\helpers\\Cache\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/SamIT-abac-helpers-Cache.html#method_set"
        },                {
            "fqsen": "\\SamIT\\abac\\helpers\\Cache\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "",
            "url": "classes/SamIT-abac-helpers-Cache.html#method_check"
        },                {
            "fqsen": "\\SamIT\\abac\\helpers\\Cache\u003A\u003AserializeGrant\u0028\u0029",
            "name": "serializeGrant",
            "summary": "",
            "url": "classes/SamIT-abac-helpers-Cache.html#method_serializeGrant"
        },                {
            "fqsen": "\\SamIT\\abac\\helpers\\Cache\u003A\u003A\u0024entries",
            "name": "entries",
            "summary": "",
            "url": "classes/SamIT-abac-helpers-Cache.html#property_entries"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\AccessChecker",
            "name": "AccessChecker",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-AccessChecker.html"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\AccessChecker\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-AccessChecker.html#method_check"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Authorizable",
            "name": "Authorizable",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Authorizable.html"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Authorizable\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Authorizable.html#method_getId"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\AuthorizableType",
            "name": "AuthorizableType",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-AuthorizableType.html"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\AuthorizableType\u003A\u003AgetAuthName\u0028\u0029",
            "name": "getAuthName",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-AuthorizableType.html#method_getAuthName"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Environment",
            "name": "Environment",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Environment.html"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Grant",
            "name": "Grant",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Grant.html"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Grant\u003A\u003AgetSource\u0028\u0029",
            "name": "getSource",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Grant.html#method_getSource"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Grant\u003A\u003AgetTarget\u0028\u0029",
            "name": "getTarget",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Grant.html#method_getTarget"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Grant\u003A\u003AgetPermission\u0028\u0029",
            "name": "getPermission",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Grant.html#method_getPermission"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Permission",
            "name": "Permission",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Permission.html"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Permission\u003A\u003AgetSourceName\u0028\u0029",
            "name": "getSourceName",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Permission.html#method_getSourceName"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Permission\u003A\u003AgetSourceId\u0028\u0029",
            "name": "getSourceId",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Permission.html#method_getSourceId"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Permission\u003A\u003AgetTargetName\u0028\u0029",
            "name": "getTargetName",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Permission.html#method_getTargetName"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Permission\u003A\u003AgetTargetId\u0028\u0029",
            "name": "getTargetId",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Permission.html#method_getTargetId"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Permission\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Permission.html#method_getId"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Permission\u003A\u003AgetSource\u0028\u0029",
            "name": "getSource",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Permission.html#method_getSource"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Permission\u003A\u003AgetTarget\u0028\u0029",
            "name": "getTarget",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Permission.html#method_getTarget"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\PermissionRepository",
            "name": "PermissionRepository",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-PermissionRepository.html"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\PermissionRepository\u003A\u003Agrant\u0028\u0029",
            "name": "grant",
            "summary": "Store\u0020a\u0020permission\u0020in\u0020persistent\u0020storage",
            "url": "classes/SamIT-abac-interfaces-PermissionRepository.html#method_grant"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\PermissionRepository\u003A\u003Arevoke\u0028\u0029",
            "name": "revoke",
            "summary": "Remove\u0020a\u0020permission\u0020from\u0020persistent\u0020storage",
            "url": "classes/SamIT-abac-interfaces-PermissionRepository.html#method_revoke"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\PermissionRepository\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-PermissionRepository.html#method_check"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\PermissionRepository\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Search\u0020for\u0020grants\u0020using\u0020a\u0020query\u002Dby\u002Dexample\u0020approach.",
            "url": "classes/SamIT-abac-interfaces-PermissionRepository.html#method_search"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Resolver",
            "name": "Resolver",
            "summary": "Implementing\u0020this\u0020inside\u0020your\u0020application\u0020allows\u0020you\u0020to\u0020authorize\u0020entities\u0020without\u0020changing\u0020the\u0020entities\u0020themselves.",
            "url": "classes/SamIT-abac-interfaces-Resolver.html"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Resolver\u003A\u003AfromSubject\u0028\u0029",
            "name": "fromSubject",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Resolver.html#method_fromSubject"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Resolver\u003A\u003AtoSubject\u0028\u0029",
            "name": "toSubject",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-Resolver.html#method_toSubject"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Rule",
            "name": "Rule",
            "summary": "Interface\u0020Rule\nRules\u0020implementing\u0020this\u0020interface\u0020can\u0020be\u0020optimized\u0020by\u0020a\u0020RuleEngine\u003B\u0020for\u0020example\u0020if\u0020the\u0020requested\u0020permission\u0020is\u0020not\u0020in\nthe\u0020list\u0020returned\u0020by\u0020\u0060getPermissions\u0028\u0029\u0060\u0020then\u0020the\u0020RuleEngine\u0020MAY\u0020skip\u0020this\u0020rule.",
            "url": "classes/SamIT-abac-interfaces-Rule.html"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Rule\u003A\u003AgetPermissions\u0028\u0029",
            "name": "getPermissions",
            "summary": "The\u0020return\u0020value\u0020of\u0020this\u0020function\u0020should\u0020not\u0020change\u0020during\u0020the\u0020lifetime\u0020of\u0020an\u0020instance",
            "url": "classes/SamIT-abac-interfaces-Rule.html#method_getPermissions"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Rule\u003A\u003AgetTargetNames\u0028\u0029",
            "name": "getTargetNames",
            "summary": "The\u0020return\u0020value\u0020of\u0020this\u0020function\u0020should\u0020not\u0020change\u0020during\u0020the\u0020lifetime\u0020of\u0020an\u0020instance",
            "url": "classes/SamIT-abac-interfaces-Rule.html#method_getTargetNames"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\Rule\u003A\u003AgetSourceNames\u0028\u0029",
            "name": "getSourceNames",
            "summary": "The\u0020return\u0020value\u0020of\u0020this\u0020function\u0020should\u0020not\u0020change\u0020during\u0020the\u0020lifetime\u0020of\u0020an\u0020instance",
            "url": "classes/SamIT-abac-interfaces-Rule.html#method_getSourceNames"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\RuleEngine",
            "name": "RuleEngine",
            "summary": "Interface\u0020RuleEngine\nImplementations\u0020should\u0020\u0028probably\u0029\u003A\n\u002D\u0020Implement\u0020some\u0020way\u0020to\u0020load\u0020\/\u0020define\u0020rules\n\u002D\u0020Implement\u0020an\u0020efficient\u0020method\u0020of\u0020deciding\u0020which\u0020rules\u0020to\u0020execute",
            "url": "classes/SamIT-abac-interfaces-RuleEngine.html"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\RuleEngine\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-RuleEngine.html#method_check"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\SimpleRule",
            "name": "SimpleRule",
            "summary": "Interface\u0020SimpleRule\nThis\u0020interface\u0020is\u0020the\u0020minimum\u0020that\u0020must\u0020be\u0020implemented\u0020by\u0020a\u0020Rule\u0020Class.",
            "url": "classes/SamIT-abac-interfaces-SimpleRule.html"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\SimpleRule\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-SimpleRule.html#method_getDescription"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces\\SimpleRule\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/SamIT-abac-interfaces-SimpleRule.html#method_execute"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\CachedReadRepository",
            "name": "CachedReadRepository",
            "summary": "Class\u0020CachedReadRepository\nCaches\u0020results\u0020from\u0020a\u0020repository\u0020in\u0020memory\u0020for\u0020the\u0020duration\u0020of\u0020a\u0020request",
            "url": "classes/SamIT-abac-repositories-CachedReadRepository.html"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\CachedReadRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-CachedReadRepository.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\CachedReadRepository\u003A\u003Agrant\u0028\u0029",
            "name": "grant",
            "summary": "Store\u0020a\u0020permission\u0020in\u0020persistent\u0020storage",
            "url": "classes/SamIT-abac-repositories-CachedReadRepository.html#method_grant"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\CachedReadRepository\u003A\u003Arevoke\u0028\u0029",
            "name": "revoke",
            "summary": "Remove\u0020a\u0020permission\u0020from\u0020persistent\u0020storage",
            "url": "classes/SamIT-abac-repositories-CachedReadRepository.html#method_revoke"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\CachedReadRepository\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-CachedReadRepository.html#method_check"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\CachedReadRepository\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Searching\u0020itself\u0020is\u0020never\u0020cached,\u0020but\u0020all\u0020search\u0020results\u0020are\u0020cached.",
            "url": "classes/SamIT-abac-repositories-CachedReadRepository.html#method_search"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\CachedReadRepository\u003A\u003A\u0024permissionRepository",
            "name": "permissionRepository",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-CachedReadRepository.html#property_permissionRepository"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\CachedReadRepository\u003A\u003A\u0024cache",
            "name": "cache",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-CachedReadRepository.html#property_cache"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\EmptyRepository",
            "name": "EmptyRepository",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-EmptyRepository.html"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\EmptyRepository\u003A\u003Agrant\u0028\u0029",
            "name": "grant",
            "summary": "Store\u0020a\u0020permission\u0020in\u0020persistent\u0020storage",
            "url": "classes/SamIT-abac-repositories-EmptyRepository.html#method_grant"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\EmptyRepository\u003A\u003Arevoke\u0028\u0029",
            "name": "revoke",
            "summary": "Remove\u0020a\u0020permission\u0020from\u0020persistent\u0020storage",
            "url": "classes/SamIT-abac-repositories-EmptyRepository.html#method_revoke"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\EmptyRepository\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-EmptyRepository.html#method_check"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\EmptyRepository\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Search\u0020for\u0020grants\u0020using\u0020a\u0020query\u002Dby\u002Dexample\u0020approach.",
            "url": "classes/SamIT-abac-repositories-EmptyRepository.html#method_search"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\FallbackRepository",
            "name": "FallbackRepository",
            "summary": "Class\u0020FallbackRepository\nThis\u0020class\u0020allows\u0020for\u0020multiple\u0020explicit\u0020permission\u0020sources.",
            "url": "classes/SamIT-abac-repositories-FallbackRepository.html"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\FallbackRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-FallbackRepository.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\FallbackRepository\u003A\u003Agrant\u0028\u0029",
            "name": "grant",
            "summary": "Store\u0020a\u0020permission\u0020in\u0020persistent\u0020storage",
            "url": "classes/SamIT-abac-repositories-FallbackRepository.html#method_grant"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\FallbackRepository\u003A\u003Arevoke\u0028\u0029",
            "name": "revoke",
            "summary": "Remove\u0020a\u0020permission\u0020from\u0020persistent\u0020storage",
            "url": "classes/SamIT-abac-repositories-FallbackRepository.html#method_revoke"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\FallbackRepository\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-FallbackRepository.html#method_check"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\FallbackRepository\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Search\u0020for\u0020grants\u0020using\u0020a\u0020query\u002Dby\u002Dexample\u0020approach.",
            "url": "classes/SamIT-abac-repositories-FallbackRepository.html#method_search"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\FallbackRepository\u003A\u003A\u0024primary",
            "name": "primary",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-FallbackRepository.html#property_primary"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\FallbackRepository\u003A\u003A\u0024secondary",
            "name": "secondary",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-FallbackRepository.html#property_secondary"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\MemoryRepository",
            "name": "MemoryRepository",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-MemoryRepository.html"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\MemoryRepository\u003A\u003AhashGrant\u0028\u0029",
            "name": "hashGrant",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-MemoryRepository.html#method_hashGrant"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\MemoryRepository\u003A\u003Agrant\u0028\u0029",
            "name": "grant",
            "summary": "Store\u0020a\u0020permission\u0020in\u0020persistent\u0020storage",
            "url": "classes/SamIT-abac-repositories-MemoryRepository.html#method_grant"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\MemoryRepository\u003A\u003Arevoke\u0028\u0029",
            "name": "revoke",
            "summary": "Remove\u0020a\u0020permission\u0020from\u0020persistent\u0020storage",
            "url": "classes/SamIT-abac-repositories-MemoryRepository.html#method_revoke"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\MemoryRepository\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-MemoryRepository.html#method_check"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\MemoryRepository\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Search\u0020for\u0020grants\u0020using\u0020a\u0020query\u002Dby\u002Dexample\u0020approach.",
            "url": "classes/SamIT-abac-repositories-MemoryRepository.html#method_search"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\MemoryRepository\u003A\u003A\u0024grants",
            "name": "grants",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-MemoryRepository.html#property_grants"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\PreloadingSourceRepository",
            "name": "PreloadingSourceRepository",
            "summary": "Repository\u0020that\u0020allows\u0020preloading\u0020permissions\u0020for\u0020a\u0020source.",
            "url": "classes/SamIT-abac-repositories-PreloadingSourceRepository.html"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\PreloadingSourceRepository\u003A\u003AserializeAuthorizable\u0028\u0029",
            "name": "serializeAuthorizable",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-PreloadingSourceRepository.html#method_serializeAuthorizable"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\PreloadingSourceRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-PreloadingSourceRepository.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\PreloadingSourceRepository\u003A\u003Agrant\u0028\u0029",
            "name": "grant",
            "summary": "Store\u0020a\u0020permission\u0020in\u0020persistent\u0020storage",
            "url": "classes/SamIT-abac-repositories-PreloadingSourceRepository.html#method_grant"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\PreloadingSourceRepository\u003A\u003Arevoke\u0028\u0029",
            "name": "revoke",
            "summary": "Remove\u0020a\u0020permission\u0020from\u0020persistent\u0020storage",
            "url": "classes/SamIT-abac-repositories-PreloadingSourceRepository.html#method_revoke"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\PreloadingSourceRepository\u003A\u003AcheckCache\u0028\u0029",
            "name": "checkCache",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-PreloadingSourceRepository.html#method_checkCache"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\PreloadingSourceRepository\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-PreloadingSourceRepository.html#method_check"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\PreloadingSourceRepository\u003A\u003ApreloadSource\u0028\u0029",
            "name": "preloadSource",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-PreloadingSourceRepository.html#method_preloadSource"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\PreloadingSourceRepository\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "Search\u0020for\u0020grants\u0020using\u0020a\u0020query\u002Dby\u002Dexample\u0020approach.",
            "url": "classes/SamIT-abac-repositories-PreloadingSourceRepository.html#method_search"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\PreloadingSourceRepository\u003A\u003A\u0024permissionRepository",
            "name": "permissionRepository",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-PreloadingSourceRepository.html#property_permissionRepository"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\PreloadingSourceRepository\u003A\u003A\u0024cache",
            "name": "cache",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-PreloadingSourceRepository.html#property_cache"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories\\PreloadingSourceRepository\u003A\u003A\u0024loadedSources",
            "name": "loadedSources",
            "summary": "",
            "url": "classes/SamIT-abac-repositories-PreloadingSourceRepository.html#property_loadedSources"
        },                {
            "fqsen": "\\SamIT\\abac\\resolvers\\AuthorizableResolver",
            "name": "AuthorizableResolver",
            "summary": "Class\u0020AuthorizableResolver\nResolves\u0020Authorizables,\u0020essentially\u0020this\u0020is\u0020an\u0020identity\u0020resolver.",
            "url": "classes/SamIT-abac-resolvers-AuthorizableResolver.html"
        },                {
            "fqsen": "\\SamIT\\abac\\resolvers\\AuthorizableResolver\u003A\u003AfromSubject\u0028\u0029",
            "name": "fromSubject",
            "summary": "",
            "url": "classes/SamIT-abac-resolvers-AuthorizableResolver.html#method_fromSubject"
        },                {
            "fqsen": "\\SamIT\\abac\\resolvers\\AuthorizableResolver\u003A\u003AtoSubject\u0028\u0029",
            "name": "toSubject",
            "summary": "",
            "url": "classes/SamIT-abac-resolvers-AuthorizableResolver.html#method_toSubject"
        },                {
            "fqsen": "\\SamIT\\abac\\resolvers\\ChainedResolver",
            "name": "ChainedResolver",
            "summary": "Class\u0020ChainedResolver\nChain\u0020multiple\u0020resolvers",
            "url": "classes/SamIT-abac-resolvers-ChainedResolver.html"
        },                {
            "fqsen": "\\SamIT\\abac\\resolvers\\ChainedResolver\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-abac-resolvers-ChainedResolver.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\resolvers\\ChainedResolver\u003A\u003AfromSubject\u0028\u0029",
            "name": "fromSubject",
            "summary": "",
            "url": "classes/SamIT-abac-resolvers-ChainedResolver.html#method_fromSubject"
        },                {
            "fqsen": "\\SamIT\\abac\\resolvers\\ChainedResolver\u003A\u003AtoSubject\u0028\u0029",
            "name": "toSubject",
            "summary": "",
            "url": "classes/SamIT-abac-resolvers-ChainedResolver.html#method_toSubject"
        },                {
            "fqsen": "\\SamIT\\abac\\resolvers\\ChainedResolver\u003A\u003A\u0024resolvers",
            "name": "resolvers",
            "summary": "",
            "url": "classes/SamIT-abac-resolvers-ChainedResolver.html#property_resolvers"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\AdminRole",
            "name": "AdminRole",
            "summary": "",
            "url": "classes/SamIT-abac-rules-AdminRole.html"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\AdminRole\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "AdminRole\u0020constructor.",
            "url": "classes/SamIT-abac-rules-AdminRole.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\AdminRole\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/SamIT-abac-rules-AdminRole.html#method_getDescription"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\AdminRole\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/SamIT-abac-rules-AdminRole.html#method_execute"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\AdminRole\u003A\u003A\u0024admins",
            "name": "admins",
            "summary": "",
            "url": "classes/SamIT-abac-rules-AdminRole.html#property_admins"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\AdminRole\u003A\u003A\u0024serializer",
            "name": "serializer",
            "summary": "",
            "url": "classes/SamIT-abac-rules-AdminRole.html#property_serializer"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\AnyoneCan",
            "name": "AnyoneCan",
            "summary": "",
            "url": "classes/SamIT-abac-rules-AnyoneCan.html"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\AnyoneCan\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-abac-rules-AnyoneCan.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\AnyoneCan\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/SamIT-abac-rules-AnyoneCan.html#method_getDescription"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\AnyoneCan\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/SamIT-abac-rules-AnyoneCan.html#method_execute"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\AnyoneCan\u003A\u003AgetPermissions\u0028\u0029",
            "name": "getPermissions",
            "summary": "The\u0020return\u0020value\u0020of\u0020this\u0020function\u0020should\u0020not\u0020change\u0020during\u0020the\u0020lifetime\u0020of\u0020an\u0020instance",
            "url": "classes/SamIT-abac-rules-AnyoneCan.html#method_getPermissions"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\AnyoneCan\u003A\u003AgetTargetNames\u0028\u0029",
            "name": "getTargetNames",
            "summary": "The\u0020return\u0020value\u0020of\u0020this\u0020function\u0020should\u0020not\u0020change\u0020during\u0020the\u0020lifetime\u0020of\u0020an\u0020instance",
            "url": "classes/SamIT-abac-rules-AnyoneCan.html#method_getTargetNames"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\AnyoneCan\u003A\u003AgetSourceNames\u0028\u0029",
            "name": "getSourceNames",
            "summary": "The\u0020return\u0020value\u0020of\u0020this\u0020function\u0020should\u0020not\u0020change\u0020during\u0020the\u0020lifetime\u0020of\u0020an\u0020instance",
            "url": "classes/SamIT-abac-rules-AnyoneCan.html#method_getSourceNames"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\AnyoneCan\u003A\u003A\u0024permission",
            "name": "permission",
            "summary": "",
            "url": "classes/SamIT-abac-rules-AnyoneCan.html#property_permission"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ExecutionCountingRule",
            "name": "ExecutionCountingRule",
            "summary": "",
            "url": "classes/SamIT-abac-rules-ExecutionCountingRule.html"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ExecutionCountingRule\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-abac-rules-ExecutionCountingRule.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ExecutionCountingRule\u003A\u003AgetExecutions\u0028\u0029",
            "name": "getExecutions",
            "summary": "",
            "url": "classes/SamIT-abac-rules-ExecutionCountingRule.html#method_getExecutions"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ExecutionCountingRule\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/SamIT-abac-rules-ExecutionCountingRule.html#method_getDescription"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ExecutionCountingRule\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/SamIT-abac-rules-ExecutionCountingRule.html#method_execute"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ExecutionCountingRule\u003A\u003AgetPermissions\u0028\u0029",
            "name": "getPermissions",
            "summary": "The\u0020return\u0020value\u0020of\u0020this\u0020function\u0020should\u0020not\u0020change\u0020during\u0020the\u0020lifetime\u0020of\u0020an\u0020instance",
            "url": "classes/SamIT-abac-rules-ExecutionCountingRule.html#method_getPermissions"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ExecutionCountingRule\u003A\u003AgetTargetNames\u0028\u0029",
            "name": "getTargetNames",
            "summary": "The\u0020return\u0020value\u0020of\u0020this\u0020function\u0020should\u0020not\u0020change\u0020during\u0020the\u0020lifetime\u0020of\u0020an\u0020instance",
            "url": "classes/SamIT-abac-rules-ExecutionCountingRule.html#method_getTargetNames"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ExecutionCountingRule\u003A\u003AgetSourceNames\u0028\u0029",
            "name": "getSourceNames",
            "summary": "The\u0020return\u0020value\u0020of\u0020this\u0020function\u0020should\u0020not\u0020change\u0020during\u0020the\u0020lifetime\u0020of\u0020an\u0020instance",
            "url": "classes/SamIT-abac-rules-ExecutionCountingRule.html#method_getSourceNames"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ExecutionCountingRule\u003A\u003A\u0024counter",
            "name": "counter",
            "summary": "",
            "url": "classes/SamIT-abac-rules-ExecutionCountingRule.html#property_counter"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ExecutionCountingRule\u003A\u003A\u0024rule",
            "name": "rule",
            "summary": "",
            "url": "classes/SamIT-abac-rules-ExecutionCountingRule.html#property_rule"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ImpliedPermission",
            "name": "ImpliedPermission",
            "summary": "This\u0020rule\u0020allows\u0020a\u0020user\u0020to\u0020do\u0020something\u0020as\u0020long\u0020as\u0020they\u0020can\u0020do\u0020something\u0020else.",
            "url": "classes/SamIT-abac-rules-ImpliedPermission.html"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ImpliedPermission\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-abac-rules-ImpliedPermission.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ImpliedPermission\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "\u0022you\u0020can\u0020...\u0020if\u0020\u005Bdescription\u005D\u0022",
            "url": "classes/SamIT-abac-rules-ImpliedPermission.html#method_getDescription"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ImpliedPermission\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/SamIT-abac-rules-ImpliedPermission.html#method_execute"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ImpliedPermission\u003A\u003AgetTargetNames\u0028\u0029",
            "name": "getTargetNames",
            "summary": "The\u0020return\u0020value\u0020of\u0020this\u0020function\u0020should\u0020not\u0020change\u0020during\u0020the\u0020lifetime\u0020of\u0020an\u0020instance",
            "url": "classes/SamIT-abac-rules-ImpliedPermission.html#method_getTargetNames"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ImpliedPermission\u003A\u003AgetPermissions\u0028\u0029",
            "name": "getPermissions",
            "summary": "The\u0020return\u0020value\u0020of\u0020this\u0020function\u0020should\u0020not\u0020change\u0020during\u0020the\u0020lifetime\u0020of\u0020an\u0020instance",
            "url": "classes/SamIT-abac-rules-ImpliedPermission.html#method_getPermissions"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ImpliedPermission\u003A\u003AgetSourceNames\u0028\u0029",
            "name": "getSourceNames",
            "summary": "The\u0020return\u0020value\u0020of\u0020this\u0020function\u0020should\u0020not\u0020change\u0020during\u0020the\u0020lifetime\u0020of\u0020an\u0020instance",
            "url": "classes/SamIT-abac-rules-ImpliedPermission.html#method_getSourceNames"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ImpliedPermission\u003A\u003A\u0024implied",
            "name": "implied",
            "summary": "",
            "url": "classes/SamIT-abac-rules-ImpliedPermission.html#property_implied"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ImpliedPermission\u003A\u003A\u0024requiredPermission",
            "name": "requiredPermission",
            "summary": "",
            "url": "classes/SamIT-abac-rules-ImpliedPermission.html#property_requiredPermission"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ImpliedPermission\u003A\u003A\u0024sourceNames",
            "name": "sourceNames",
            "summary": "",
            "url": "classes/SamIT-abac-rules-ImpliedPermission.html#property_sourceNames"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\ImpliedPermission\u003A\u003A\u0024targetNames",
            "name": "targetNames",
            "summary": "",
            "url": "classes/SamIT-abac-rules-ImpliedPermission.html#property_targetNames"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\PermissionMatchRule",
            "name": "PermissionMatchRule",
            "summary": "",
            "url": "classes/SamIT-abac-rules-PermissionMatchRule.html"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\PermissionMatchRule\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-abac-rules-PermissionMatchRule.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\PermissionMatchRule\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/SamIT-abac-rules-PermissionMatchRule.html#method_getDescription"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\PermissionMatchRule\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/SamIT-abac-rules-PermissionMatchRule.html#method_execute"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\PermissionMatchRule\u003A\u003AgetPermissions\u0028\u0029",
            "name": "getPermissions",
            "summary": "The\u0020return\u0020value\u0020of\u0020this\u0020function\u0020should\u0020not\u0020change\u0020during\u0020the\u0020lifetime\u0020of\u0020an\u0020instance",
            "url": "classes/SamIT-abac-rules-PermissionMatchRule.html#method_getPermissions"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\PermissionMatchRule\u003A\u003AgetTargetNames\u0028\u0029",
            "name": "getTargetNames",
            "summary": "The\u0020return\u0020value\u0020of\u0020this\u0020function\u0020should\u0020not\u0020change\u0020during\u0020the\u0020lifetime\u0020of\u0020an\u0020instance",
            "url": "classes/SamIT-abac-rules-PermissionMatchRule.html#method_getTargetNames"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\PermissionMatchRule\u003A\u003AgetSourceNames\u0028\u0029",
            "name": "getSourceNames",
            "summary": "The\u0020return\u0020value\u0020of\u0020this\u0020function\u0020should\u0020not\u0020change\u0020during\u0020the\u0020lifetime\u0020of\u0020an\u0020instance",
            "url": "classes/SamIT-abac-rules-PermissionMatchRule.html#method_getSourceNames"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\PermissionMatchRule\u003A\u003A\u0024pattern",
            "name": "pattern",
            "summary": "",
            "url": "classes/SamIT-abac-rules-PermissionMatchRule.html#property_pattern"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\PermissionMatchRule\u003A\u003A\u0024sourceNames",
            "name": "sourceNames",
            "summary": "",
            "url": "classes/SamIT-abac-rules-PermissionMatchRule.html#property_sourceNames"
        },                {
            "fqsen": "\\SamIT\\abac\\rules\\PermissionMatchRule\u003A\u003A\u0024targetNames",
            "name": "targetNames",
            "summary": "",
            "url": "classes/SamIT-abac-rules-PermissionMatchRule.html#property_targetNames"
        },                {
            "fqsen": "\\SamIT\\abac\\values\\Authorizable",
            "name": "Authorizable",
            "summary": "Simple\u0020immutable\u0020Authorizable\u0020implementation",
            "url": "classes/SamIT-abac-values-Authorizable.html"
        },                {
            "fqsen": "\\SamIT\\abac\\values\\Authorizable\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-abac-values-Authorizable.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\values\\Authorizable\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/SamIT-abac-values-Authorizable.html#method_getId"
        },                {
            "fqsen": "\\SamIT\\abac\\values\\Authorizable\u003A\u003AgetAuthName\u0028\u0029",
            "name": "getAuthName",
            "summary": "",
            "url": "classes/SamIT-abac-values-Authorizable.html#method_getAuthName"
        },                {
            "fqsen": "\\SamIT\\abac\\values\\Authorizable\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/SamIT-abac-values-Authorizable.html#property_id"
        },                {
            "fqsen": "\\SamIT\\abac\\values\\Authorizable\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/SamIT-abac-values-Authorizable.html#property_name"
        },                {
            "fqsen": "\\SamIT\\abac\\values\\Grant",
            "name": "Grant",
            "summary": "Simple\u0020value\u0020object",
            "url": "classes/SamIT-abac-values-Grant.html"
        },                {
            "fqsen": "\\SamIT\\abac\\values\\Grant\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-abac-values-Grant.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\abac\\values\\Grant\u003A\u003AgetSource\u0028\u0029",
            "name": "getSource",
            "summary": "",
            "url": "classes/SamIT-abac-values-Grant.html#method_getSource"
        },                {
            "fqsen": "\\SamIT\\abac\\values\\Grant\u003A\u003AgetTarget\u0028\u0029",
            "name": "getTarget",
            "summary": "",
            "url": "classes/SamIT-abac-values-Grant.html#method_getTarget"
        },                {
            "fqsen": "\\SamIT\\abac\\values\\Grant\u003A\u003AgetPermission\u0028\u0029",
            "name": "getPermission",
            "summary": "",
            "url": "classes/SamIT-abac-values-Grant.html#method_getPermission"
        },                {
            "fqsen": "\\SamIT\\abac\\values\\Grant\u003A\u003A\u0024source",
            "name": "source",
            "summary": "",
            "url": "classes/SamIT-abac-values-Grant.html#property_source"
        },                {
            "fqsen": "\\SamIT\\abac\\values\\Grant\u003A\u003A\u0024target",
            "name": "target",
            "summary": "",
            "url": "classes/SamIT-abac-values-Grant.html#property_target"
        },                {
            "fqsen": "\\SamIT\\abac\\values\\Grant\u003A\u003A\u0024permission",
            "name": "permission",
            "summary": "",
            "url": "classes/SamIT-abac-values-Grant.html#property_permission"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\SamIT\\abac",
            "name": "abac",
            "summary": "",
            "url": "namespaces/samit-abac.html"
        },                {
            "fqsen": "\\SamIT",
            "name": "SamIT",
            "summary": "",
            "url": "namespaces/samit.html"
        },                {
            "fqsen": "\\SamIT\\abac\\engines",
            "name": "engines",
            "summary": "",
            "url": "namespaces/samit-abac-engines.html"
        },                {
            "fqsen": "\\SamIT\\abac\\exceptions",
            "name": "exceptions",
            "summary": "",
            "url": "namespaces/samit-abac-exceptions.html"
        },                {
            "fqsen": "\\SamIT\\abac\\helpers",
            "name": "helpers",
            "summary": "",
            "url": "namespaces/samit-abac-helpers.html"
        },                {
            "fqsen": "\\SamIT\\abac\\interfaces",
            "name": "interfaces",
            "summary": "",
            "url": "namespaces/samit-abac-interfaces.html"
        },                {
            "fqsen": "\\SamIT\\abac\\repositories",
            "name": "repositories",
            "summary": "",
            "url": "namespaces/samit-abac-repositories.html"
        },                {
            "fqsen": "\\SamIT\\abac\\resolvers",
            "name": "resolvers",
            "summary": "",
            "url": "namespaces/samit-abac-resolvers.html"
        },                {
            "fqsen": "\\SamIT\\abac\\rules",
            "name": "rules",
            "summary": "",
            "url": "namespaces/samit-abac-rules.html"
        },                {
            "fqsen": "\\SamIT\\abac\\values",
            "name": "values",
            "summary": "",
            "url": "namespaces/samit-abac-values.html"
        }            ]
);
